/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_logging_config_EventLogCollector */

#ifndef _Included_org_logging_config_EventLogCollector
#define _Included_org_logging_config_EventLogCollector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_logging_config_EventLogCollector
 * Method:    collectWindowsLogs
 * Signature: (J)[Ljava/util/Map;
 */
JNIEXPORT jobjectArray JNICALL Java_org_logging_config_EventLogCollector_collectWindowsLogs
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
